language: python
python:
  - "3.5"
sudo: required
before_install:
- pushd travis-ci-test && ./setupenv.sh && popd

script:
- pushd travis-ci-test && ./runtest_basic.sh && popd
- pushd travis-ci-test && ./runtest_kill.sh && popd
- pushd travis-ci-test && ./runtest_rebuild.sh && popd

